# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d38780862e636db193f4f616c83663d"
application_url = "https://ooo-louisiana-adapter-avon.trycloudflare.com"
embedded = true
name = "BadgeBoost"
handle = "badgeboost"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes"

[auth]
redirect_urls = [
  "https://ooo-louisiana-adapter-avon.trycloudflare.com/auth/callback",
  "https://ooo-louisiana-adapter-avon.trycloudflare.com/auth/shopify/callback",
  "https://ooo-louisiana-adapter-avon.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "urbann-curate.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
